name: Documenting and Testing
title: Documenting Regulated Applications
subtitle: A Practical Guide
email: wwgoodridge@gmail.com
description: Website with templates for documenting and testing applications to meet FDA and EMA regulations. Templates are based on GAMP best practices and ISO security standards with detailed instructions for easy customization.
baseurl: /regdocs
url: https://wgoodridge.github.io/regdocs
author: W Goodridge

kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
