name: Documenting and Testing
title: Documenting Regulated Applications
subtitle: A Practical Guide
url:
description: Website with templates for documenting and testing FDA and EU regulated life science applications. Templates are based on GAMP5, and ISO security standards, most can be output in several formats (doc, pdf, html, markdown), with enough detail for easy customization.
baseurl: /regdocs
url: https://wgoodridge.github.io/regdocs
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
